# =====================================================
# Oh My Zsh configuration
# =====================================================
export ZSH="$HOME/.oh-my-zsh"
plugins=(git fzf-tab zsh-autosuggestions zsh-syntax-highlighting)

# Prefer zsh's bundled completions (e.g. native _git) over Homebrew
# formulas' bash-wrapper shims, which silently fail without bash-completion.
# Must be before oh-my-zsh.sh (which calls compinit).
[ -d /opt/homebrew/share/zsh/functions ] && fpath=(/opt/homebrew/share/zsh/functions $fpath)

source $ZSH/oh-my-zsh.sh

# -----------------------------------------------------
# User configuration
# -----------------------------------------------------
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

# Generated by the e6data CLI so its flags and environments stay in sync.
source <(engine --completion=zsh)

# =====================================================
# Shell options
# =====================================================
setopt sharehistory

# =====================================================
# Completion system
# =====================================================

# Completion styling (used by fzf-tab when present, otherwise native compsys)
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza --color=always --icons $realpath'

# Completer chain: try the command's registered completer first, then fall
# through to filename completion. Without _files at the end, commands whose
# completer returns no candidates (e.g. `aws s3 cp src ./`, `git add ./`)
# leave you with nothing — zsh won't offer local paths unless we ask it to.
zstyle ':completion:*' completer _complete _files

# Include hidden files in completion (scoped to compsys; does not affect glob expansions)
_comp_options+=(globdots)

# Eagerly source Homebrew completion helpers that use `complete -C` (e.g. aws).
# Their _foo wrappers try to self-bootstrap on first <tab> but fire too late
# and fall through to filename completion.
autoload -U bashcompinit && bashcompinit
for _completer in /opt/homebrew/share/zsh/site-functions/*_completer.sh; do
    [ -f "$_completer" ] && source "$_completer"
done
unset _completer

# =====================================================
# Prompt
# =====================================================
eval "$(starship init zsh)"

# =====================================================
# Tool integrations
# =====================================================

# -----------------------------------------------------
# FZF support
# -----------------------------------------------------
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# -----------------------------------------------------
# Television support:
# ctrl + t -> smart autocompletion
# -----------------------------------------------------
eval "$(tv init zsh)"

# -----------------------------------------------------
# Atuin (shell history) — loaded AFTER tv so it wins the ctrl+r binding.
# ctrl + r -> searchable history (SQLite-backed: timestamps, exit codes, cwd)
# -----------------------------------------------------
eval "$(atuin init zsh)"

# -----------------------------------------------------
# NVM lazy load (NVM_DIR set in .profile)
# -----------------------------------------------------
nvm() {
    unset -f nvm
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use
    nvm "$@"
}
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# -----------------------------------------------------
# Bun completions (zsh-specific file)
# -----------------------------------------------------
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# -----------------------------------------------------
# Pyenv init (shell-specific evals)
# -----------------------------------------------------
eval "$(pyenv init -)"
if pyenv commands | grep -q virtualenv-init; then
    eval "$(pyenv virtualenv-init -)"
fi

# -----------------------------------------------------
# SDKMAN (must be after other PATH modifications)
# -----------------------------------------------------
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# =====================================================
# zsh-specific PATH
# =====================================================
# scripts folder relative to this dotfile (zsh-specific parameter expansion)
export PATH="$PATH:${${(%):-%x}:A:h}/scripts"

# =====================================================
# zsh-specific aliases and functions
# =====================================================
alias please='sudo $(fc -ln -1)'
alias sz='source ~/.zshrc'
alias idea='open -na "IntelliJ IDEA.app" --args "$@"'
alias rover='open -na "RustRover.app" --args "$@"'

# =====================================================
# Zoxide (MUST be last — wraps `cd` and the prompt hook,
# so it has to load after pyenv/nvm/sdkman, which install
# their own chpwd hooks. zoxide's doctor warns if anything
# re-wraps these after its init.)
# =====================================================
eval "$(zoxide init zsh --cmd cd --hook prompt)"

# Restore oh-my-zsh's dirstack aliases (1..9) — zoxide's `cd` wrapper
# swallows `cd -N`, so call the builtin directly.
for i in {1..9}; do alias "$i"="builtin cd -$i"; done
unset i

export PATH="/Library/TeX/texbin:$PATH"

# opencode
export PATH=/Users/zeelrajodiya/.opencode/bin:$PATH
