service_tier = "fast"
model = "gpt-5.6-sol"
model_context_window = 600000
model_auto_compact_token_limit = 500000
model_reasoning_effort = "medium"
plan_mode_reasoning_effort = "high"
approvals_reviewer = "auto_review"
notify = [
    "/Users/zeelrajodiya/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    "turn-ended",
]

[projects."/Users/zeelrajodiya/Projects/e6data/e6-native-executor/e6-planner-interface"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-native-executor"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-planner"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/linuxConfig"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-planner-interface"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-native-executor/e6-workspace-services-thrift"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/repos/datafusion"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-engine-cli"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-regression-test"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-query-optimizer"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-calcite"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/repos/wiz-music"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-native-executor/e6-datafusion"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6data-query-engine"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Documents/Codex/2026-08-09/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/e6data/e6-query-engine"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Projects/repos/resume-v2"]
trust_level = "trusted"

[projects."/Users/zeelrajodiya/Library/CloudStorage/OneDrive-Personal/OneDrive Documents/notes/work"]
trust_level = "trusted"

[tui]
status_line = [
    "model-with-reasoning",
    "project-name",
    "git-branch",
    "run-state",
    "context-remaining",
    "five-hour-limit",
    "weekly-limit",
]
status_line_use_colors = true
theme = "ansi"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.node_repl]
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120.0

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.803.41515"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"
CODEX_HOME = "/Users/zeelrajodiya/.codex"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "323bc3e687e17d7e377238d9f4c69111c4d0e6219103b6316d8c52082489533b"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/zeelrajodiya/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[features]
terminal_resize_reflow = true
memories = true
js_repl = false

[marketplaces.openai-bundled]
last_updated = "2026-08-19T07:27:40Z"
source_type = "local"
source = "/Users/zeelrajodiya/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.claude-plugins-official]
last_updated = "2026-08-25T11:47:27Z"
last_revision = "b819188d2eea14e0400556ca29dbd1179a7c595b"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.openai-primary-runtime]
last_updated = "2026-08-19T07:29:09Z"
source_type = "local"
source = "/Users/zeelrajodiya/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."code-simplifier@claude-plugins-official"]
enabled = true

[plugins."commit-commands@claude-plugins-official"]
enabled = true

[plugins."context7@claude-plugins-official"]
enabled = true

[plugins."firecrawl@claude-plugins-official"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."atlassian-rovo@openai-curated-remote"]
enabled = false

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "323bc3e687e17d7e377238d9f4c69111c4d0e6219103b6316d8c52082489533b"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/zeelrajodiya/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
followUpQueueMode = "queue"

[desktop.open-in-target-preferences]
global = "zed"
